---
image: jembi/platform
defaultTargetLauncher: swarm
disableKubernetes: true
disableIG: true
disableCustomTargetSelection: true
packages:
  - id: interoperability-layer-openhim
    name: Interoperability Layer - OpenHIM
  - id: reverse-proxy-nginx
    name: Reverse Proxy - NGINX
  - id: fhir-datastore-hapi-fhir
    name: FHIR Data Store - HAPI-FHIR
  - id: message-bus-kafka
    name: Message Bus - Kafka
  - id: message-bus-helper-hapi-proxy
    name: Message Bus Helper Package - Hapi Proxy
  - id: kafka-unbundler-consumer
    name: Kafka Unbundler Consumer
  - id: kafka-mapper-consumer
    name: Kafka Mapper Consumer
  - id: analytics-datastore-clickhouse
    name: Analytics Datastore Clickhouse
  - id: dashboard-visualiser-superset
    name: Dashboard Visualiser Superset
