projectName: Cares-on-platform
image: jembi/platform:1.5.0
logPath: /tmp/logs

packages:
  - cares-on-platform
  - reverse-proxy-nginx
  - monitoring

customPackages:
  - id: cares-on-platform
    path: ../cares-on-platform

profiles:
  - name: local
    packages:
      - cares-on-platform
      - monitoring
    envFiles:
      - ./.env.local
    dev: true

  - name: prod
    packages:
      - cares-on-platform
      - reverse-proxy-nginx
      - monitoring
    envFiles:
      - ./.env.prod
