projectName: Cares-on-platform
image: jembi/platform:workshop-testing
logPath: /tmp/logs

packages:
  - interoperability-layer-openhim
  - cares-on-platform
  - reverse-proxy-nginx
  - message-bus-helper-hapi-proxy
  - monitoring

customPackages:
  - id: cares-on-platform
    path: ../cares-on-platform

profiles:
  - name: local
    packages:
      - interoperability-layer-openhim
      - cares-on-platform
      - message-bus-helper-hapi-proxy
    envFiles:
      - ./.env.local
    dev: true

  - name: prod
    packages:
      - interoperability-layer-openhim
      - cares-on-platform
      - reverse-proxy-nginx
      - message-bus-helper-hapi-proxy
    envFiles:
      - ./.env.prod
