projectName: Cares-on-platform
image: jembi/platform:latest
logPath: /tmp/logs

packages:
    - cares-on-platform
    - reverse-proxy-nginx
    - elastic-monitoring-metricbeats-filebeats
    - system-monitoring-prometheus-grafana

customPackages:
  - id: cares-on-platform
    path: ../cares-on-platform

profiles:
  - name: local
    packages:
      - cares-on-platform
    envFiles:
      - ./.env.local
    dev: true

  - name: prod
    packages:
      - cares-on-platform
      - reverse-proxy-nginx
      - elastic-monitoring-metricbeats-filebeats
      - system-monitoring-prometheus-grafana
    envFiles:
      - ./.env.prod
