version: '3.9'

services:
  # container for executing config import scripts for setting up initial config
  cares-clickhouse-config-importer:
    image: node:erbium-alpine
    deploy:
      restart_policy:
        condition: none
    environment:
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
      CLICKHOUSE_PORT: ${CLICKHOUSE_PORT}
    configs:
      - source: cares-clickhouse-config-clickhouseConfig.js
        target: /clickhouseConfig.js
    command: sh -c "cd / && npm i clickhouse && node /clickhouseConfig.js"
    networks:
      clickhouse:

  cares-superset-config-importer:
    image: node:erbium-alpine
    deploy:
      restart_policy:
        condition: none
    environment:
      SUPERSET_SERVICE_NAME: 'dashboard-visualiser-superset'
      SUPERSET_API_PORT: 8088
      SUPERSET_API_PASSWORD: ${SUPERSET_API_PASSWORD}
      SUPERSET_API_USERNAME: ${SUPERSET_API_USERNAME}
      CONFIG_FILE: ${SUPERSET_CONFIG_FILE}
      SUPERSET_SSL: ${SUPERSET_SSL}
    configs:
      - source: cares-superset-config-supersetConfig.js
        target: /supersetConfig.js
      - source: cares-superset-config-superset-export.zip
        target: /superset-export.zip
    command: sh -c "cd / && npm i axios form-data && node /supersetConfig.js"
    networks:
      clickhouse:

  hapi-fhir-config-importer:
    image: node:erbium-alpine
    environment:
      HAPI_FHIR_BASE_URL: http://hapi-fhir:8080/fhir
      FHIR_IG_URL: ${FHIR_IG_URL}
      NODE_ENV: 'production'
    configs:
      - source: cares-hapi-fhir-fhirConfig.js
        target: /fhirConfig.js
    command: sh -c "cd / && npm i axios@v1.1.3 adm-zip && npm i wait-on -g && wait-on -t 600000 http-get://hapi-fhir:8080 && node /fhirConfig.js"
    networks:
      hapi-fhir:

configs:
  cares-clickhouse-config-clickhouseConfig.js:
    file: ./analytics-datastore-clickhouse/clickhouseConfig.js
    name: cares-clickhouse-config-clickhouseConfig.js-${cares_clickhouse_config_clickhouseConfig_js_DIGEST:?err}
    labels:
      name: clickhouse
  cares-superset-config-supersetConfig.js:
    file: ./dashboard-visualiser-superset/supersetConfig.js
    name: cares-superset-config-supersetConfig.js-${cares_superset_config_supersetConfig_js_DIGEST:?err}
    labels:
      name: superset
  cares-superset-config-superset-export.zip:
    file: ./dashboard-visualiser-superset/superset-export.zip
    name: cares-superset-config-superset-export.zip-${cares_superset_config_superset_export_zip_DIGEST:?err}
    labels:
      name: superset
  cares-hapi-fhir-fhirConfig.js:
    file: ./hapi-fhir/fhirConfig.js
    name: cares-hapi-fhir-fhirConfig.js-${cares_hapi_fhir_fhirConfig_js_DIGEST:?err}
    labels:
      name: hapi-fhir

networks:
  clickhouse:
    name: clickhouse_public
    external: true
  hapi-fhir:
    name: hapi-fhir_public
    external: true
